# Use postgres/example user/password credentials
version: "3.1"

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./pgdata:${POSTGRES_LOCATION}

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
